// KariGhar - Complete Local Mock Database (Constants)

export const INITIAL_ARTISANS = [
  {
    id: "meera-devi",
    name: "Meera Devi",
    role: "Master Potter",
    location: "Bhuj, Kutch District",
    experience: "30 Years of Experience",
    badges: ["UNESCO Heritage Awardee", "National Award Winner"],
    photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=300&auto=format&fit=crop",
    quote: "I learned the language of clay from my grandmother. Every vase I make carries the rhythm of my ancestors' songs.",
    story: "In the dry and dusty dunes of Bhuj, Meera Devi has spent three decades refining the art of Kutch pottery. Harvesting clay after the summer monsoons, she shapes each item on a traditional stone wheel, using local red soil that gets its signature high-iron orange glow from pit firing with agricultural husks. Each etching is done completely from memory using traditional bone tools, preserving motifs passed down through five generations of her family."
  },
  {
    id: "parvati-devi",
    name: "Parvati Devi",
    role: "Master Weaver",
    location: "Maheshwar, Madhya Pradesh",
    experience: "40+ Years of Experience",
    badges: ["UNESCO Heritage Grantee", "Master Craftswoman"],
    photo: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?q=80&w=300&auto=format&fit=crop",
    quote: "Every thread holds the story of my ancestors. Digital commerce gives our family a sustainable future.",
    story: "Parvati Devi is a legend in the historic town of Maheshwar. Working from her wooden handloom that occupies the center of her ancestral cottage, she spends weeks weaving a single handloom silk saree. Specializing in Ajrakh hand-block printing and fine zari embroidery, her creations carry tales of rivers, temples, and forests. Through digital enablement, she is now sharing this legacy with collectors worldwide, passing the craft to her daughters."
  }
];

export const INITIAL_PRODUCTS = [
  {
    id: "earthen-sanctuary-vase",
    title: "Earthen Sanctuary Vase",
    subtitle: "HAND-THROWN • KUTCH DISTRICT",
    price: 4250,
    rating: 5.0,
    reviewCount: 48,
    category: "Pottery & Ceramics",
    district: "Bhuj",
    artisanId: "meera-devi",
    images: [
      "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1565192647048-f997ded87958?q=80&w=600&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1597484211029-f073d1015243?q=80&w=600&auto=format&fit=crop"
    ],
    tags: ["Organic Clay", "Hand-Painted", "Sustainable"],
    stockStatus: "In stock, ready to ship (Kutch)",
    description: "Inspired by the shifting dunes of the Thar desert, each Earthen Sanctuary Vase is hand-thrown using local red clay. The intricate geometric patterns are etched by hand using traditional bone tools, a process that takes over six hours per piece. Fired in a community open pit using dried husks, it features a warm earthy hue that perfectly complements modern minimalist spaces.",
    materials: [
      "Raw Terracotta Clay: High-iron content clay from the Kutch region, known for its deep orange-red hue after firing.",
      "Organic Linseed Finish: Sealed with a light coat of natural linseed oil to provide a soft sheen without synthetic chemicals."
    ],
    process: [
      { step: "1", title: "Natural Sourcing", desc: "Clay is harvested from local riverbeds after the monsoon season." },
      { step: "2", title: "Traditional Etching", desc: "Patterns are drawn from memory, selecting 300-year-old tribal motifs." },
      { step: "3", title: "Open Pit Firing", desc: "Vases are fired in a community pit using sustainable husks." }
    ]
  },
  {
    id: "terracotta-uru",
    title: "Terracotta Uru",
    subtitle: "HAND-THROWN • KUTCH DISTRICT",
    price: 3400,
    rating: 4.8,
    reviewCount: 32,
    category: "Pottery & Ceramics",
    district: "Bhuj",
    artisanId: "meera-devi",
    images: ["https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=80&w=600&auto=format&fit=crop"],
    tags: ["Handmade", "Eco-friendly"],
    stockStatus: "In stock, ready to ship",
    description: "A classic water carafe reimagined as an art piece. Handcrafted with traditional high-fire techniques, providing a stunning natural cooling texture and structural elegance.",
    materials: ["Local riverbed clay", "Clay slip glaze"],
    process: []
  },
  {
    id: "indigo-silk-stole",
    title: "Indigo Silk Stole",
    subtitle: "HAND-WOVEN • VARANASI DISTRICT",
    price: 7200,
    rating: 4.9,
    reviewCount: 41,
    category: "Hand-loom Textiles",
    district: "Varanasi",
    artisanId: "parvati-devi",
    images: ["https://images.unsplash.com/photo-1590736969955-71cb94801759?q=80&w=600&auto=format&fit=crop"],
    tags: ["Handmade", "Organic Indigo Dye"],
    stockStatus: "In stock, ready to ship",
    description: "Woven on wooden handlooms in Varanasi using raw Mulberry silk. Hand-dyed using organic wild indigo vats, presenting a breathtaking sapphire finish with traditional borders.",
    materials: ["100% Mulberry Silk", "Organic Indigo Dye"],
    process: []
  },
  {
    id: "carved-walnut-bowl",
    title: "Carved Walnut Bowl",
    subtitle: "HAND-CARVED • KASHMIR DISTRICT",
    price: 4850,
    rating: 4.7,
    reviewCount: 29,
    category: "Wooden Carvings",
    district: "Kashmir",
    artisanId: "mysore-collective",
    images: ["https://images.unsplash.com/photo-1606001044761-a8a6770f5d8a?q=80&w=600&auto=format&fit=crop"],
    tags: ["Eco-friendly", "Premium Wood"],
    stockStatus: "In stock, ready to ship",
    description: "Sculpted from single blocks of seasoned wild walnut trees in the Kashmir Valley. Smoothly finished with raw organic wax, showcasing gorgeous dark natural grains.",
    materials: ["Wild Walnut Wood", "Natural Bee's Wax Finish"],
    process: []
  },
  {
    id: "dhokra-metal-nandi",
    title: "Dhokra Metal Nandi",
    subtitle: "LOST WAX CASTING • BASTAR DISTRICT",
    price: 12000,
    rating: 5.0,
    reviewCount: 15,
    category: "Metalwork (Dhokra)",
    district: "Bastar",
    artisanId: "bastar-collective",
    images: ["https://images.unsplash.com/photo-1606293926075-69a007f4e8b3?q=80&w=600&auto=format&fit=crop"],
    tags: ["Handmade", "Ancient Castings"],
    stockStatus: "Limited Edition (3 left)",
    description: "Crafted using the 4,000-year-old lost-wax casting technique (Dhokra) by tribal metal smiths of Bastar. Solid brass metal structure representing the sacred bull Nandi.",
    materials: ["Recycled Brass Scrap", "Natural Bee's Wax Mold", "Alluvial River Soil"],
    process: []
  },
  {
    id: "jaipur-blue-platter",
    title: "Jaipur Blue Platter",
    subtitle: "QUARTZ CLAY • JAIPUR DISTRICT",
    price: 2100,
    rating: 4.6,
    reviewCount: 22,
    category: "Pottery & Ceramics",
    district: "Jaipur",
    artisanId: "royal-clay",
    images: ["https://images.unsplash.com/photo-1610701596007-11502861dcfa?q=80&w=600&auto=format&fit=crop"],
    tags: ["Handmade", "Eco-friendly"],
    stockStatus: "In stock",
    description: "Classic Jaipur blue pottery platter made without clay. Uses a quartz-sand blend hand-painted in traditional floral cobalt motifs.",
    materials: ["Quartz Sand", "Cobalt Oxide Glaze", "Glass Powders"],
    process: []
  },
  {
    id: "pashmina-heritage-wrap",
    title: "Pashmina Heritage Wrap",
    subtitle: "KASHMIR PASHM • HIMALAYAS",
    price: 28500,
    rating: 5.0,
    reviewCount: 19,
    category: "Hand-loom Textiles",
    district: "Kashmir",
    artisanId: "parvati-devi",
    images: ["https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?q=80&w=600&auto=format&fit=crop"],
    tags: ["Handmade", "Rare Pashm Wool"],
    stockStatus: "Limited Collection",
    description: "Woven by hand in high altitudes using the rare undercoat wool of the Himalayan Changthangi goat. Breathtakingly soft, exceptionally warm, and incredibly light.",
    materials: ["100% Changthangi Pashm Wool"],
    process: []
  },
  {
    id: "earthbound-vase",
    title: "Earthbound Vase",
    subtitle: "TERRACOTTA CARVING • ARANYA CRAFTS",
    price: 4850,
    rating: 4.9,
    reviewCount: 120,
    category: "Pottery & Ceramics",
    district: "Bhuj",
    artisanId: "meera-devi",
    images: ["https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?q=80&w=600&auto=format&fit=crop"],
    tags: ["Handmade", "Eco-friendly"],
    stockStatus: "In stock",
    description: "Our signature high-necked terracotta vase. Features exquisite hand-etched bands showcasing forest and tribal motifs, providing a rustic and grounding touch to dining or hallway tables.",
    materials: ["100% Organic Terracotta Clay", "Raw ochre slip paints"],
    process: []
  },
  {
    id: "silk-lotus-throw",
    title: "Silk Lotus Throw",
    subtitle: "HANDLOOM SILK • VARANASI DISTRICT",
    price: 1850,
    rating: 4.8,
    reviewCount: 97,
    category: "Hand-loom Textiles",
    district: "Varanasi",
    artisanId: "parvati-devi",
    images: ["https://images.unsplash.com/photo-1600121848594-d8644e57abab?q=80&w=600&auto=format&fit=crop"],
    tags: ["Handmade", "Zari Embroidery"],
    stockStatus: "In stock",
    description: "A gorgeous cushion throw woven in soft Banarasi silk, detailed with small gold zari lotus motifs and finished with thick organic cotton tassels.",
    materials: ["Mulberry Silk thread", "Gold Zari thread"],
    process: []
  },
  {
    id: "indigo-dream-cup",
    title: "Indigo Dream Cup",
    subtitle: "COBALT BLUE GLAZE • ROYAL CLAY",
    price: 950,
    rating: 5.0,
    reviewCount: 34,
    category: "Pottery & Ceramics",
    district: "Jaipur",
    artisanId: "royal-clay",
    images: ["https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?q=80&w=600&auto=format&fit=crop"],
    tags: ["Eco-friendly", "Hand-painted"],
    stockStatus: "In stock",
    description: "A beautiful handcrafted ceramic mug detailed with floral cobalt carvings, designed to fit comfortably in your hands and bring heritage warmth to your tea or coffee routines.",
    materials: ["Quartz clay blend", "Lead-free cobalt glaze"],
    process: []
  },
  {
    id: "sandalwood-keepsake",
    title: "Sandalwood Keepsake",
    subtitle: "FRAGRANT CARVING • MYSORE DISTRICT",
    price: 6200,
    rating: 4.7,
    reviewCount: 58,
    category: "Wooden Carvings",
    district: "Mysore",
    artisanId: "mysore-collective",
    images: ["https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?q=80&w=600&auto=format&fit=crop"],
    tags: ["Fragrant Wood", "Hand-Carved"],
    stockStatus: "Only 5 left",
    description: "An absolute masterwork carved out of genuine, aromatic Mysore Sandalwood. Elaborately etched with ancient folklore murals, maintaining a subtle woody fragrance that lasts a lifetime.",
    materials: ["Aromatic Mysore Sandalwood Wood"],
    process: []
  },
  {
    id: "ripple-clay-bowl",
    title: "Ripple Clay Bowl",
    price: 1400,
    rating: 4.5,
    reviewCount: 16,
    category: "Pottery & Ceramics",
    district: "Bhuj",
    artisanId: "meera-devi",
    images: ["https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?q=80&w=600&auto=format&fit=crop"],
    tags: ["Handmade"],
    stockStatus: "In stock",
    description: "A wide, elegant dining platter bowl hand-pressed with delicate wave carvings along the outer rim.",
    materials: ["Terracotta Clay"],
    process: []
  },
  {
    id: "heritage-pitcher",
    title: "Heritage Pitcher",
    price: 2050,
    rating: 4.7,
    reviewCount: 23,
    category: "Pottery & Ceramics",
    district: "Bhuj",
    artisanId: "meera-devi",
    images: ["https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?q=80&w=600&auto=format&fit=crop"],
    tags: ["Handmade"],
    stockStatus: "In stock",
    description: "A tall, beautiful clay water pitcher styled after ancient Kutch storage containers, offering natural thermodynamic cooling.",
    materials: ["Terracotta clay"],
    process: []
  },
  {
    id: "sunlight-holders",
    title: "Sunlight Holders",
    price: 990,
    rating: 4.9,
    reviewCount: 38,
    category: "Wooden Carvings",
    district: "Mysore",
    artisanId: "mysore-collective",
    images: ["https://images.unsplash.com/photo-1598971861713-54ad16a7e72e?q=80&w=600&auto=format&fit=crop"],
    tags: ["Hand-Carved"],
    stockStatus: "In stock",
    description: "Set of 2 small sandalwood tea-light candles holders, carved with floral lattice (Jaali) patterns that throw beautiful shadow shapes.",
    materials: ["Sandalwood wood"],
    process: []
  },
  {
    id: "ancestral-platter",
    title: "Ancestral Platter",
    price: 2200,
    rating: 4.8,
    reviewCount: 20,
    category: "Pottery & Ceramics",
    district: "Jaipur",
    artisanId: "royal-clay",
    images: ["https://images.unsplash.com/photo-1610701596007-11502861dcfa?q=80&w=600&auto=format&fit=crop"],
    tags: ["Lead-free", "Eco-friendly"],
    stockStatus: "In stock",
    description: "A flat blue quartz platter painted in radial geometric sunflower lines, representing cosmic cycles.",
    materials: ["Quartz sand glaze"],
    process: []
  }
];

export const INITIAL_REVIEWS = [
  {
    id: "r1",
    productId: "earthen-sanctuary-vase",
    reviewerName: "Ananya G.",
    rating: 5,
    verified: true,
    date: "Verified Buyer - Oct 2025",
    text: "The texture is incredible. You can literally feel the artisan's fingerprints in the clay. It adds such a grounding warmth to my home office. Arrived perfectly packaged in sustainable husks."
  },
  {
    id: "r2",
    productId: "earthen-sanctuary-vase",
    reviewerName: "David M.",
    rating: 4,
    verified: true,
    date: "Verified Buyer - Aug 2025",
    text: "Stunning piece of art. A bit smaller than I expected from the photos, but the detail in the hand-carving is breathtaking. Truly a premium piece."
  },
  {
    id: "r3",
    productId: "indigo-silk-stole",
    reviewerName: "Rajesh K.",
    rating: 5,
    verified: true,
    date: "Verified Buyer - Dec 2025",
    text: "The indigo color is rich, and the silk feels extremely soft and strong. You can tell it was made on a traditional loom. It is worth every rupee."
  }
];
